server {

  listen 80;
  # nginx in ascolto sulla porta HTTP 80


  # ---------------- INVENTARIO API ----------------

  location /users {

    proxy_pass http://backend:5000;
    # inoltra richieste verso inventario-api

    proxy_set_header Host $host;
    # passa hostname originale client

    proxy_set_header X-Real-IP $remote_addr;
    # passa IP reale client
  }


  # ---------------- OSSERVABILITA API ----------------

  # location /health {

  #   proxy_pass http://osservabilita-api:5000;
  #   # inoltra richieste healthcheck
    # verso osservabilita-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  


  location /processes {

    proxy_pass http://osservabilita-api:4000;
    # inoltra richieste process runtime
    # verso osservabilita-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }

    # ---------------- PROCESSI API ----------------

  location /health {

    proxy_pass http://processi-api:3140;
    # inoltra richieste healthcheck
    # verso processi-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }
}