server {

  listen 80;
  # nginx in ascolto sulla porta HTTP 80


  # =========================================================
  # INVENTARIO API
  # =========================================================

  location /inventario-api/users {

    proxy_pass http://inventario-api:5000/users;
    # inoltra richieste users
    # verso inventario-api

    proxy_set_header Host $host;
    # passa hostname originale client

    proxy_set_header X-Real-IP $remote_addr;
    # passa IP reale client
  }


  location /inventario-api/health {

    proxy_pass http://inventario-api:5000/health;
    # healthcheck inventario-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }



  # =========================================================
  # OSSERVABILITA API
  # =========================================================

  location /osservabilita-api/health {

    proxy_pass http://osservabilita-api:4000/health;
    # healthcheck osservabilita-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }


  location /osservabilita-api/processes {

    proxy_pass http://osservabilita-api:4000/processes;
    # runtime/process analysis

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }



  # =========================================================
  # PROCESSI API
  # =========================================================

  location /processi-api/health {

    proxy_pass http://processi-api:3140/health;
    # healthcheck processi-api

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }


  location /processi-api/processes {

    proxy_pass http://processi-api:3140/processes;
    # Linux process runtime endpoint

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
  }

}